tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "fzf"
brew "ghq"
brew "git"
brew "jq"
brew "neovim"
brew "postgresql", restart_service: true
brew "ripgrep"
brew "swagger-codegen"
brew "tmux"
cask "alacritty"
cask "font-hackgen-nerd"
cask "google-chrome"
cask "visual-studio-code"
