modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L

keymap:
  - name: Emacs
    application:
      not: [Alacritty]
    remap:
      # Cursor
      C-b: { with_mark: left }
      C-f: { with_mark: right }
      C-p: { with_mark: up }
      C-n: { with_mark: down }
      # Forward/Backward word
      M-b: { with_mark: C-left }
      M-f: { with_mark: C-right }
      # Beginning/End of line
      C-a: { with_mark: home }
      C-e: { with_mark: end }
      # Delete
      C-d: [delete, { set_mark: false }]
      # M-d: [C-delete, { set_mark: false }]
